#!/usr/bin/env python3
"""Export per-case intervention table rows from analyze_per_case JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from safeconfirm.evaluation.benchmark_cases import load_benchmark_cases

DEFAULT_CASES_PATH = Path(__file__).resolve().parents[1] / "safeconfirm/data/benchmark_cases_e2e.yaml"


def _escalation(row: dict) -> str:
    interventions = row.get("interventions") or {}
    if interventions.get("SOURCE_AWARE_CONFIRM"):
        return f"CONF({interventions['SOURCE_AWARE_CONFIRM']})"
    if row.get("repair_attempts"):
        return f"REP({row['repair_attempts']})"
    if interventions.get("BLOCK"):
        return f"BLK({interventions['BLOCK']})"
    return "ALLOW"


def _short_id(case_id: str) -> str:
    short = case_id.removeprefix("ws_").removeprefix("bk_").replace("_e2e", "")
    short = short.replace("_benign_explicit", "_benign")
    return short


def _latex_tool(tool_name: str) -> str:
    return tool_name.replace("_", "\\_")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export per-case LaTeX table from per_case_summary.json")
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--cases-path", type=Path, default=DEFAULT_CASES_PATH)
    args = parser.parse_args()

    tool_by_id = {case.id: case.tool_name for case in load_benchmark_cases(args.cases_path)}
    summary = json.loads(args.input.read_text())
    rows = sorted(summary["cases"], key=lambda r: int(r["user_task_id"].split("_")[-1]))

    lines = [
        "% Auto-generated by util_scripts/export_per_case_appendix.py",
        "\\begin{tabular}{@{}l@{\\hspace{0.5em}}l@{\\hspace{0.5em}}cc@{\\hspace{0.5em}}r@{}}",
        "\\toprule",
        "Case & Tool & TSR & ASR & Esc. \\\\",
        "\\midrule",
    ]
    for row in rows:
        case_id = row["case_id"]
        tool = _latex_tool(tool_by_id.get(case_id, "?"))
        util = "\\checkmark" if row["utility"] else "--"
        if row.get("benign"):
            asr = "n/a"
        else:
            asr = "\\checkmark" if row.get("attack_succeeded") else "--"
        lines.append(
            f"{_short_id(case_id).replace('_', '\\_')} & {tool} & {util} & {asr} & {_escalation(row)} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])

    text = "\n".join(lines) + "\n"
    output = args.output or args.input.with_name("per_case_table.tex")
    output.write_text(text)
    print(f"Wrote {output} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
